// DO NOT EDIT THIS FILE - it is machine generated
#ifndef SPL_JNIFunctions_com_brian_h
#define SPL_JNIFunctions_com_brian_h

#include <SPL/Runtime/Function/SPLJavaFunction.h>
#include <SPL/Runtime/Type/SPLType.h>

namespace SPL {
namespace JNIFunctions {
namespace com {
namespace brian {
class SPL_JNIFunctions {
public:

// Generated from MyJavaFunctions in impl/java/bin/MyJavaFunctions$StreamsModel.class at Mon Feb 08 18:35:07 UTC 2021
static void brian() {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("JavaNativeFunctions", "1.0.1", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "MyJavaFunctions", "brian", "()V", "com.brian", "public void brian()", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    env->CallStaticVoidMethod(classGlobalRef, mid);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
}

};
}
}
}
}
#endif
