create table jonathan.ipfix (
 CAPTURETIME                   TIMESTAMP                        ,
 MESSAGENUMBER                 BIGINT                         ,
 IPPROTOCOL                    CHARACTER VARYING(10)             ,
 IPSOURCEADDRESS               CHARACTER VARYING(20)             ,
 IPSOURCEPORT                  SMALLINT                         ,
 IPDESTINATIONADDRESS          CHARACTER VARYING(20)            ,
 IPDESTINATIONPORT             SMALLINT                          ,
 OCTETDELTACOUNT               BIGINT                          ,
 PACKETDELTACOUNT              BIGINT                          ,
 PROTOCOLIDENTIFIER            BYTEINT                          ,
 IPCLASSOFSERVICE              BYTEINT                          ,
 TCPCONTROLBITS                SMALLINT                          ,
 SOURCETRANSPORTPORT           SMALLINT                         ,
 SOURCEIPV4ADDRESS             CHARACTER VARYING(20)             ,
 SOURCEIPV4PREFIXLENGTH        BYTEINT                          ,
 INGRESSINTERFACE              INTEGER                          ,
 DESTINATIONTRANSPORTPORT      SMALLINT                          ,
 DESTINATIONIPV4ADDRESS        CHARACTER VARYING(20)            ,
 DESTINATIONIPV4PREFIXLENGTH   BYTEINT                          ,
 EGRESSINTERFACE               INTEGER                          ,
 IPNEXTHOPIPV4ADDRESS          CHARACTER VARYING(20)             ,
 BGPSOURCEASNUMBER             INTEGER                          ,
 BGPDESTINATIONASNUMBER        INTEGER                          ,
 BGPNEXTHOPIPV4ADDRESS         CHARACTER VARYING(20)             ,
 POSTMCASTPACKETDELTACOUNT     BIGINT                          ,
 POSTMCASTOCTETDELTACOUNT      BIGINT                          ,
 FLOWENDSYSUPTIME              CHARACTER VARYING(20)             ,
 FLOWSTARTSYSUPTIME            CHARACTER VARYING(20)             ,
 POSTOCTETDELTACOUNT           BIGINT                          ,
 POSTPACKETDELTACOUNT          BIGINT                          ,
 MINIMUMIPTOTALLENGTH          BIGINT                          ,
 MAXIMUMIPTOTALLENGTH          BIGINT                          ,
 SOURCEIPV6ADDRESS             CHARACTER VARYING(39)             ,
 DESTINATIONIPV6ADDRESS        CHARACTER VARYING(39)             ,
 SOURCEIPV6PREFIXLENGTH        BYTEINT                          ,
 DESTINATIONIPV6PREFIXLENGTH   BYTEINT                          ,
 FLOWLABELIPV6                 INTEGER                          ,
 ICMPTYPECODEIPV4              SMALLINT                          ,
 IGMPTYPE                      BYTEINT                          ,
 FLOWACTIVETIMEOUT             INTEGER                          ,
 FLOWIDLETIMEOUT               INTEGER                          ,
 EXPORTEDOCTETTOTALCOUNT       BIGINT                          ,
 EXPORTEDMESSAGETOTALCOUNT     BIGINT                          ,
 EXPORTEDFLOWRECORDTOTALCOUNT  BIGINT                          ,
 SOURCEIPV4PREFIX              CHARACTER VARYING(20)             ,
 DESTINATIONIPV4PREFIX         CHARACTER VARYING(20)             ,
 MPLSTOPLABELTYPE              BYTEINT                          ,
 MPLSTOPLABELIPV4ADDRESS       CHARACTER VARYING(20)             ,
 MINIMUMTTL                    BYTEINT                          ,
 MAXIMUMTTL                    BYTEINT                          ,
 FRAGMENTIDENTIFICATION        INTEGER                          ,
 POSTIPCLASSOFSERVICE          BYTEINT                          ,
 SOURCEMACADDRESS              CHARACTER VARYING(17)             ,
 POSTDESTINATIONMACADDRESS     CHARACTER VARYING(17)             ,
 VLANID                        SMALLINT                          ,
 POSTVLANID                    SMALLINT                          ,
 IPVERSION                     BYTEINT                          ,
 FLOWDIRECTION                 BYTEINT                          ,
 IPNEXTHOPIPV6ADDRESS          CHARACTER VARYING(39)             ,
 BGPNEXTHOPIPV6ADDRESS         CHARACTER VARYING(39)             ,
 IPV6EXTENSIONHEADERS          INTEGER                          ,
 MPLSTOPLABELSTACKSECTION      CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION2        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION3        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION4        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION5        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION6        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION7        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION8        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION9        CHARACTER VARYING(3)             ,
 MPLSLABELSTACKSECTION10       CHARACTER VARYING(3)             ,
 DESTINATIONMACADDRESS         CHARACTER VARYING(17)             ,
 POSTSOURCEMACADDRESS          CHARACTER VARYING(17)             ,
 OCTETTOTALCOUNT               BIGINT                          ,
 PACKETTOTALCOUNT              BIGINT                          ,
 FRAGMENTOFFSET                SMALLINT                          ,
 MPLSVPNROUTEDISTINGUISHER     CHARACTER VARYING(8)             ,
 BGPNEXTADJACENTASNUMBER       INTEGER                          ,
 BGPPREVADJACENTASNUMBER       INTEGER                          ,
 EXPORTERIPV4ADDRESS           CHARACTER VARYING(20)             ,
 EXPORTERIPV6ADDRESS           CHARACTER VARYING(20)             ,
 DROPPEDOCTETDELTACOUNT        BIGINT                          ,
 DROPPEDPACKETDELTACOUNT       BIGINT                          ,
 DROPPEDOCTETTOTALCOUNT        BIGINT                          ,
 DROPPEDPACKETTOTALCOUNT       BIGINT                          ,
 FLOWENDREASON                 BYTEINT                          ,
 COMMONPROPERTIESID            BIGINT                          ,
 OBSERVATIONPOINTID            INTEGER                          ,
 ICMPTYPECODEIPV6              SMALLINT ,
 MPLSTOPLABELIPV6ADDRESS       CHARACTER VARYING(39)             ,
 LINECARDID                    INTEGER                          ,
 PORTID                        INTEGER                          ,
 METERINGPROCESSID             INTEGER                          ,
 EXPORTINGPROCESSID            INTEGER                          ,
 TEMPLATEID                    SMALLINT                          ,
 WLANCHANNELID                 BYTEINT                          ,
 WLANSSID                      CHARACTER VARYING(20)             ,
 FLOWID                        BIGINT                          ,
 OBSERVATIONDOMAINID           INTEGER                          ,
 FLOWSTARTSECONDS              CHARACTER VARYING(20)             ,
 FLOWENDSECONDS                CHARACTER VARYING(20)             ,
 FLOWSTARTMILLISECONDS         CHARACTER VARYING(20)             ,
 FLOWENDMILLISECONDS           CHARACTER VARYING(20)             ,
 FLOWSTARTMICROSECONDS         CHARACTER VARYING(20)             ,
 FLOWENDMICROSECONDS           CHARACTER VARYING(20)             ,
 FLOWSTARTNANOSECONDS          CHARACTER VARYING(20)             ,
 FLOWENDNANOSECONDS            CHARACTER VARYING(20)             ,
 FLOWSTARTDELTAMICROSECONDS    INTEGER                          ,
 FLOWENDDELTAMICROSECONDS      INTEGER                          ,
 SYSTEMINITTIMEMILLISECONDS    CHARACTER VARYING(20)             ,
 FLOWDURATIONMILLISECONDS      CHARACTER VARYING(20)             ,
 FLOWDURATIONMICROSECONDS      CHARACTER VARYING(20)             ,
 OBSERVEDFLOWTOTALCOUNT        BIGINT                          ,
 IGNOREDPACKETTOTALCOUNT       BIGINT                          ,
 IGNOREDOCTETTOTALCOUNT        BIGINT                          ,
 NOTSENTFLOWTOTALCOUNT         BIGINT                          ,
 NOTSENTPACKETTOTALCOUNT       BIGINT                          ,
 NOTSENTOCTETTOTALCOUNT        BIGINT                          ,
 DESTINATIONIPV6PREFIX         CHARACTER VARYING(20)             ,
 SOURCEIPV6PREFIX              CHARACTER VARYING(20)             ,
 POSTOCTETTOTALCOUNT           BIGINT                          ,
 POSTPACKETTOTALCOUNT          BIGINT                          ,
 FLOWKEYINDICATOR              BIGINT                          ,
 POSTMCASTPACKETTOTALCOUNT     BIGINT                          ,
 POSTMCASTOCTETTOTALCOUNT      BIGINT                          ,
 ICMPTYPEIPV4                  BYTEINT                          ,
 ICMPCODEIPV4                  BYTEINT                          ,
 ICMPTYPEIPV6                  BYTEINT                          ,
 ICMPCODEIPV6                  BYTEINT                          ,
 UDPSOURCEPORT                 SMALLINT                          ,
 UDPDESTINATIONPORT            SMALLINT                          ,
 TCPSOURCEPORT                 SMALLINT                          ,
 TCPDESTINATIONPORT            SMALLINT                          ,
 TCPSEQUENCENUMBER             INTEGER                          ,
 TCPACKNOWLEDGEMENTNUMBER      INTEGER                          ,
 TCPWINDOWSIZE                 SMALLINT                          ,
 TCPURGENTPOINTER              SMALLINT                          ,
 TCPHEADERLENGTH               BYTEINT                          ,
 IPHEADERLENGTH                BYTEINT                          ,
 TOTALLENGTHIPV4               SMALLINT                          ,
 PAYLOADLENGTHIPV6             SMALLINT                          ,
 IPTTL                         BYTEINT                          ,
 NEXTHEADERIPV6                BYTEINT                          ,
 MPLSPAYLOADLENGTH             INTEGER                          ,
 IPDIFFSERVCODEPOINT           BYTEINT                          ,
 IPPRECEDENCE                  BYTEINT                          ,
 FRAGMENTFLAGS                 BYTEINT                          ,
 OCTETDELTASUMOFSQUARES        BIGINT                          ,
 OCTETTOTALSUMOFSQUARES        BIGINT                          ,
 MPLSTOPLABELTTL               BYTEINT                          ,
 MPLSLABELSTACKLENGTH          INTEGER                          ,
 MPLSLABELSTACKDEPTH           INTEGER                          ,
 MPLSTOPLABELEXP               BYTEINT                          ,
 IPPAYLOADLENGTH               INTEGER                          ,
 UDPMESSAGELENGTH              SMALLINT                          ,
 ISMULTICAST                   BYTEINT                          ,
 IPV4IHL                       BYTEINT                          ,
 IPV4OPTIONS                   INTEGER                          ,
 TCPOPTIONS                    BIGINT                          ,
 PADDINGOCTETS                 CHARACTER VARYING(8)             ,
 COLLECTORIPV4ADDRESS          CHARACTER VARYING(20)             ,
 COLLECTORIPV6ADDRESS          CHARACTER VARYING(39)             ,
 EXPORTINTERFACE               INTEGER                          ,
 EXPORTPROTOCOLVERSION         BYTEINT                          ,
 EXPORTTRANSPORTPROTOCOL       BYTEINT                          ,
 COLLECTORTRANSPORTPORT        SMALLINT                          ,
 EXPORTERTRANSPORTPORT         SMALLINT                          ,
 TCPSYNTOTALCOUNT              BIGINT                          ,
 TCPFINTOTALCOUNT              BIGINT                          ,
 TCPRSTTOTALCOUNT              BIGINT                          ,
 TCPPSHTOTALCOUNT              BIGINT                          ,
 TCPACKTOTALCOUNT              BIGINT                          ,
 TCPURGTOTALCOUNT              BIGINT                          ,
 IPTOTALLENGTH                 BIGINT                          ,
 POSTMPLSTOPLABELEXP           BYTEINT                          ,
 TCPWINDOWSCALE                SMALLINT                          
)
Distribute on random;
